project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"

lang: en
author-meta: "Joshua Kunst"

website:
  title: "Visual Data Sketches"
  description: "Interactive data visualizations, visual stories, maps, and experiments."
  site-url: "https://jkunst.com/visual-data-sketches/"
  google-analytics: "G-ECZ9XLT78C"
  open-graph: true
  twitter-card: true
  search: false
  navbar:
    title: "jk"
    pinned: true
    right:
      - text: Blog ↗
        href: "https://jkunst.com/blog/"
        target: _blank
      - text: Visual Data Sketches
        href: index.qmd
      - text: GitHub ↗
        href: "https://github.com/jbkunst/visual-data-sketches"
        target: _blank

format:
  html:
    theme: cosmo
    canonical-url: true
    toc: false
    anchor-sections: false
    smooth-scroll: true
    link-external-newwindow: true

execute:
  freeze: auto
