<script>
window.RD3M_I18N = {
  es: {
    ui: {
      previous: "Anterior", next: "Siguiente", language: "Idioma",
      brand: "Descomposición del riesgo de crédito por AGE, COHORT y PERIOD",
      cohort: "Cohorte", age: "Edad", period: "Período", loans_at_risk: "Préstamos", defaults_3m: "Defaults",
      baseline: "Nivel base", residual: "Residuo", observed_rd3m: "RD3M observado",
      loans_at_risk_caption: "préstamos en riesgo", defaults_caption: "defaults en 3 meses",
      defaults_within_age: "defaults en este grupo de edad", selected_cell: "Celda seleccionada",
      weighted_by_loans: "Los préstamos ponderan el promedio", cells_in: "Celdas en",
      contributions_note: "Marcador: RD3M observado. Componentes: nivel base más contribuciones ajustadas secuenciales.",
      baseline_logit: "logit base", age_logit_effect: "efecto AGE en logit",
      cohort_logit_effect: "efecto COHORT en logit", period_logit_effect: "efecto PERIOD en logit"
    },
    scenes: {
      "portfolio": {"kicker":"1 · Riesgo de cartera","title":"Midiendo el riesgo","text":"Existen varias maneras de medir el riesgo de una cartera. Una forma usual de ver su evolución es la tasa de default: los defaults sobre los préstamos en riesgo al inicio de un período. Puede medirse a distintos horizontes. Aquí usamos tres meses, de modo que RD3M son los defaults desde el mes \\(t\\) hasta \\(t+2\\), divididos por los préstamos en riesgo en \\(t\\)."},
      "focus": {"kicker":"2 · Un período","title":"Miremos un momento","text":"Ahora miremos {period}. El RD3M de la cartera en este punto es un solo número, pero se construye a partir de muchos préstamos."},
      "ratio": {"kicker":"3 · Numerador y denominador","title":"¿Qué significa realmente esta tasa?","text":"El denominador son todos los préstamos en riesgo al inicio de {period}. Tres meses después, el numerador es el subconjunto que cayó en default. Estos son todos los préstamos y defaults del período focal, no una muestra."},
      "ages": {"kicker":"4 · Dentro del denominador","title":"Los préstamos no son todos iguales","text":"Mantengamos la misma población de préstamos y separémosla por grupos de edad. Cada grupo representa una edad distinta del préstamo, y los defaults permanecen asignados al grupo de edad en que ocurren."},
      "base": {"kicker":"5 · Agrupar los préstamos","title":"Agrupar préstamos en celdas cohorte × edad","text":"Agrupamos los préstamos individuales en celdas definidas por cohorte y edad. Cada celda contiene su cohorte, edad, préstamos en riesgo y defaults durante los tres meses siguientes. Hay muchas combinaciones, por lo que este ejemplo usa una ventana pequeña. Los agregados posteriores usarán toda la historia disponible."},
      "rd3m": {"kicker":"6 · RD3M por celda","title":"Calcular el riesgo en cada celda","text":"Para cada cohorte \\(c\\) y edad \\(a\\), dividimos los defaults por los préstamos en riesgo para obtener \\(RD3M_{c,a}\\). Ponderar estas tasas por préstamos dentro de un período calendario reconstruye el RD3M de cartera de ese período. Una ventana de cinco edades y cinco períodos mantiene legible este ejemplo."},
      "q": {"kicker":"7 · Ajustar celdas con cero","title":"Agregar la probabilidad ajustada","text":"Algunas celdas cohorte-edad no registran defaults durante los tres meses, por lo que su tasa bruta es cero. Antes de llevar las tasas a la escala logit del siguiente paso, aplicamos un ajuste pequeño: sumamos 0.5 a los defaults y 0.5 a los no-defaults. El numerador gana 0.5 y el denominador gana 1. Así evitamos valores de borde en la transformación posterior y apenas cambiamos las celdas grandes."},
      "logit": {"kicker":"8 · Cambiar de escala","title":"Pasar a log-odds","text":"RD3M es una probabilidad, acotada entre cero y uno. Sus odds comparan la probabilidad de default con la de no default; al tomar su logaritmo, esa comparación pasa a una escala aditiva y sin cotas. Allí podemos sumar un nivel común y las contribuciones de AGE, COHORT y PERIOD. Aplicamos la transformación solo a la probabilidad ajustada: \\(y_{c,a}=\\operatorname{logit}(q_{c,a})\\)."},
      "mu": {"kicker":"9 · Nivel global","title":"Comenzar desde un nivel ponderado","text":"El nivel base \\(\\mu\\) es el promedio de los log odds ajustados entre todas las celdas, ponderado por préstamos. Es el nivel común de cartera antes de describir cómo difieren edad, cohorte y período calendario."},
      "r0": {"kicker":"10 · Primer residuo","title":"¿Qué queda después del nivel base?","text":"Para cada celda, restamos \\(\\mu\\) de \\(y_{c,a}=\\operatorname{logit}(q_{c,a})\\). El residuo \\(r_{c,a}^{(0)}\\) es la desviación de esa celda respecto del nivel común de cartera en escala de log odds. Es el punto de partida para AGE."},
      "age": {"kicker":"11 · AGE","title":"Estimar AGE un grupo a la vez","text":"Partiendo de \\(r_{c,a}^{(0)}\\), para cada edad \\(a\\), \\(A_a\\) es su promedio entre todas las cohortes \\(c\\) de esa edad, ponderado por préstamos. Es la desviación promedio de log odds asociada a ese grupo de edad, antes de separar cohorte y período."},
      "r1": {"kicker":"12 · Residuo después de AGE","title":"Restar la contribución AGE","text":"Restamos \\(A_a\\) del residuo inicial \\(r_{c,a}^{(0)}\\). El remanente \\(r_{c,a}^{(1)}\\) es lo que AGE no explica y pasa a ser el insumo para COHORT."},
      "cohort": {"kicker":"13 · COHORT","title":"Estimar COHORT una cohorte a la vez","text":"Para cada cohorte \\(c\\), \\(C_c\\) es el promedio ponderado por préstamos del residuo después de AGE, \\(r_{c,a}^{(1)}\\), entre todas las edades \\(a\\) de esa cohorte. Es la desviación de log-odds específica de cohorte que queda después de considerar AGE."},
      "r2": {"kicker":"14 · Residuo después de COHORT","title":"Restar la contribución COHORT","text":"Restamos \\(C_c\\) del residuo después de AGE, \\(r_{c,a}^{(1)}\\). El resultado, \\(r_{c,a}^{(2)}\\), es lo que queda para que PERIOD lo explique."},
      "period": {"kicker":"15 · PERIOD","title":"Terminar con el tiempo calendario","text":"El residuo \\(r_{c,a}^{(2)}\\) contiene lo que dejan AGE y COHORT. Para cada período calendario \\(p\\), \\(P_p\\) es su promedio entre todas las celdas con \\(p_{c,a}=p\\), ponderado por préstamos. Es la desviación común de tiempo calendario que queda después de AGE y COHORT."},
      "r3": {"kicker":"16 · Residuo final","title":"Lo que queda es un residuo de celda","text":"Restamos \\(P_{p_{c,a}}\\) de \\(r_{c,a}^{(2)}\\). La descomposición secuencial queda completa, y \\(r_{c,a}^{(3)}\\) es la parte específica de cada celda que los efectos sistemáticos no explican."},
      "fitted": {"kicker":"17 · Logit ajustado","title":"Sumar los efectos sistemáticos","text":"Los tres efectos sistemáticos ya están estimados. Los sumamos al nivel base común para obtener el logit ajustado \\(\\hat y_{c,a}\\). Es la parte explicada antes de agregar el residuo final de celda."},
      "reconstruct-logit": {"kicker":"18 · Reconstruir el logit","title":"Recuperar una identidad existente","text":"El logit ajustado y el residuo final recuperan exactamente el logit ajustado original. Es una verificación de igualdad, no un cálculo nuevo: \\(y_{c,a}=\\operatorname{logit}(q_{c,a})\\) ya se calculó en el paso 8."},
      "risk-focus": {"kicker":"19 · Volver a la escala RD3M","title":"Explicar un riesgo observado","text":"Tomemos una celda cohorte-edad: la cohorte {cohort} a edad {age}, observada en {period}, tiene RD3M de {rd3m}. Ahora queremos explicar ese riesgo observado mediante el nivel base, AGE, COHORT, PERIOD y la contribución restante de la celda."},
      "risk-inputs": {"kicker":"20 · Ingredientes en escala de riesgo","title":"Definir la representación en escala de riesgo","text":"El objetivo es una representación aditiva del propio RD3M. No podemos obtenerla aplicando logits inversos a los efectos de logit por separado, porque el logit inverso no es lineal. Conservamos el RD3M observado y los ingredientes finales del logit: \\(\\mu\\), AGE, COHORT, PERIOD, logit ajustado \\(\\hat y\\) y \\(r^{(3)}\\). Los residuos intermedios anteriores ya no son necesarios."},
      "risk-base": {"kicker":"21 · Riesgo base","title":"Comenzar una trayectoria secuencial","text":"Un efecto en logit no tiene un significado fijo en puntos porcentuales: su impacto sobre el riesgo depende del nivel desde el que partimos. Por eso comenzamos en la probabilidad base común, \\(\\mu'=\\operatorname{plogis}(\\mu)\\)."},
      "risk-age": {"kicker":"22 · AGE en escala de riesgo","title":"Crear A′","text":"\\(\\operatorname{plogis}(\\mu+A_a)\\) es el riesgo predicho después de agregar AGE, antes de COHORT y PERIOD. \\(A'_a\\) es el cambio desde el nivel base común hasta ese riesgo: el primer incremento secuencial."},
      "risk-cohort": {"kicker":"23 · COHORT en escala de riesgo","title":"Crear C′","text":"COHORT es el siguiente cambio incremental, después de que ya están presentes el nivel base y AGE."},
      "risk-period": {"kicker":"24 · PERIOD en escala de riesgo","title":"Crear P′","text":"PERIOD es el incremento sistemático final. En este punto, los componentes suman el riesgo ajustado de cada celda."},
      "risk-residual": {"kicker":"25 · Remanente de celda","title":"Crear e′","text":"El remanente final en escala de riesgo es la brecha entre el riesgo ajustado y el RD3M observado. Cierra exactamente la identidad de celda."},
      "risk-identity": {"kicker":"26 · Identidad RD3M","title":"Los componentes de riesgo reconstruyen cada celda","text":"Por construcción, los cinco términos en escala de riesgo suman el RD3M observado en cada celda cohorte-edad. Esta identidad permite agregar los efectos al nivel de cartera."},
      "period-aggregate": {"kicker":"27 · Agregar por período","title":"Ponderar los efectos de celda por préstamos","text":"La ventana de ejemplo termina aquí: estos valores usan todas las celdas cohorte-edad de la historia completa de la cartera. Dentro de cada período calendario, agregamos cada componente usando Préstamos como ponderadores. Los términos con barra son las contribuciones de cartera y reconstruyen RD3M de cartera."},
      "portfolio-return": {"kicker":"28 · RD3M de cartera","title":"Volver a la cartera original","text":"El mismo cálculo período a período ahora se aplica a la cartera completa. Volvemos a la serie RD3M inicial; los siguientes pasos agregarán sus componentes agregados uno a uno."},
      "portfolio-base": {"kicker":"29 · Nivel base","title":"Comenzar la descomposición de cartera","text":"Para cada período de cartera, comenzamos con el riesgo base común. Es constante porque \\(\\mu\\) es constante, y aquí se expresa en puntos porcentuales de riesgo."},
      "portfolio-age": {"kicker":"30 · Agregar AGE","title":"Agregar la contribución AGE","text":"Luego agregamos el incremento AGE de cada período, ponderado por préstamos. AGE puede aumentar o reducir el riesgo respecto del nivel base común."},
      "portfolio-cohort": {"kicker":"31 · Agregar COHORT","title":"Agregar la contribución COHORT","text":"Luego agregamos el incremento COHORT ponderado por préstamos. Junto con el nivel base y AGE, entrega el riesgo implicado por esas tres partes de la descomposición."},
      "portfolio-period": {"kicker":"32 · Agregar PERIOD","title":"Agregar la contribución PERIOD","text":"PERIOD completa el riesgo ajustado sistemático. Nivel base, AGE, COHORT y PERIOD pueden ser positivos o negativos respecto de cero."},
      "portfolio-residual": {"kicker":"33 · Cerrar con el residuo","title":"Agregar la contribución residual","text":"Finalmente agregamos el residuo, el remanente de celda después de las componentes sistemáticas. Juntas, las cinco componentes suman el RD3M de cartera observado."},
      "portfolio-reconstructed": {"kicker":"34 · RD3M reconstruido","title":"Los componentes recuperan la serie original","text":"La suma de cada componente con signo recupera exactamente la serie RD3M original de la cartera. Esta es la representación final en escala de riesgo: nivel base, AGE, COHORT, PERIOD y la contribución restante de la celda. Es útil para explicar, pero no es única: las contribuciones dependen del orden secuencial elegido para el cálculo. La igualdad se cumple porque la descomposición se construyó para cerrar en cada celda antes de agregar."},
      "effect-facets": {"kicker":"35 · Leer las componentes","title":"¿Qué puede mover el riesgo de cartera?","text":"Estas trayectorias separan las fuentes de cambios en RD3M. AGE refleja la mezcla de edades de la cartera, por lo que su contribución también debería tender a mantenerse estable cuando esa mezcla se mantiene estable. Una contribución COHORT alta puede señalar diferencias entre originaciones particulares que conviene investigar, como una campaña, un cambio de originación o la mezcla de clientes. Una contribución PERIOD alta es común a las celdas y puede señalar un shock de calendario o una crisis. COHORT y PERIOD son señales descriptivas, no evidencia causal. Todos los paneles usan la misma escala vertical y el residuo es cercano a cero por construcción."}
    }
  }
};
</script>
